### ISSUE TITLE
Mana Pie Chart

### ISSUE THREAD

**Issue by emhann** [accassid/turnbased-alpha#11]
![mana pie char](https://user-images.githubusercontent.com/15115668/34530891-86085c26-f07e-11e7-9df1-7c9a0025f7cc.PNG)

Even if an artifact can produce any color mana, it should be restricted to the colors available in the deck.

**Comment by accassid** [comment]
The issue with this, is a deck like Sen Triplets wants to know what colors it can produce outside of the commander's identity.

**Comment by emhann** [comment]
true. maybe make it a deck option then? I feel like that's much more the exception than the rule, and it's off-putting to see five colors in the mana chart. How do other deckbuilding sites handle it?
