### ISSUE TITLE
Card Type Arranging

### ISSUE THREAD

**Issue by emhann** [accassid/turnbased-alpha#19]
![sorcery](https://user-images.githubusercontent.com/15115668/34532902-ef1ffe10-f085-11e7-90be-202805c53dd1.PNG)

Dynamically move things around? Sorcery could easily be under planeswalkers and still fit the screen. 

Also, Maybeboard shouldn't be intermixed with 'In-The-Deck' card categories.

**Comment by MikeDrewitt** [comment]
@accassid perhaps here we might want to consider moving the sideboard and maybeboards to a new deck container? Then build out the secondary deck container the same way as the primary?
 
This addresses one issue mentioned above

**Comment by accassid** [comment]
It's actually already dynamically moving things around based on a greedy algorithm, which is theoretically not the most optimal but is the best option for performance. The issue that's coming up there is I'm overriding the algorithm to make Commander, Sideboard, and Maybeboard appear in the right most colemn, in their own if they can or sharing it if they can't. I suppose I could make it so they would never share unless there's only one column?

**Comment by emhann** [comment]
Commander, Sideboard, Maybe board in the right most is fine, just having sorceries over there, under maybeboard, was concerning.
