### ISSUE TITLE
Tribal Cards end up in their own category

### ISSUE THREAD

**Issue by Teri511** [accassid/turnbased-alpha#25]
Tribal cards sit in their own category instead of whatever type of card they are

I.E: 
Crib Swap falls under "Tribal" instead of "Instant"

**Comment by RedPandaRevolution** [comment]
Likewise, creature enchantments end up in enchantments without any way to move them.

Interestingly, in the deck statistics, these cards count toward both enchantments and creatures (as they should). Does this also happen with tribal cards?
